run:
  timeout: 5m
linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - revive
issues:
  exclude-rules:
    - path: _templ\.go
      linters: [all]
